<table class="table" id="review-table" style="empty-cells: hide">
    <thead>
    <tr>
        <th></th>
        <th>CPU frequency</th>
        <th>Number of CPU cores</th>
        <th>Video RAM</th>
        <th>RAM</th>
        <th>Storage space</th>
    </tr>
    </thead>
    <tbody>
    <tr valign="middle">
        <td>
            <?php if (!empty($error)): echo '<small class="text-danger">' . $error . '</small>'; else:?>Your PC:<?php endif; ?>
        </td>
        <td>
            <?php echo $user->cpufreq ?> GHz
        </td>
        <td>
            <?php echo $user->cpucores ?>
        </td>
        <td>
            <?php echo $user->gpuvram ?> GB
        </td>
        <td>
            <?php echo $user->ram ?> GB
        </td>
        <td>
            <?php echo $user->storagespace ?> GB
        </td>
    </tr>
    <tr valign="middle">
        <td>
            <?php echo $game->name ?> - minimum requirements:
        </td>
        <td>
            <?php echo $game->cpufreq ?> GHz
        </td>
        <td>
            <?php echo $game->cpucores ?>
        </td>
        <td>
            <?php echo $game->gpuvram ?> GB
        </td>
        <td>
            <?php echo $game->ram ?> GB
        </td>
        <td>
            <?php echo $game->storagespace ?> GB
        </td>
    </tr>
    <?php if (empty($error)): ?>
    <tr valign="middle">
        <td>
            Results:
        </td>
        <td>
            <?php if($game->cpufreq <= $user->cpufreq): ?> <i class="fa fa-check"></i><?php else: ?><i class="fa fa-times"></i><?php endif; ?>
        </td>
        <td>
            <?php if($game->cpucores <= $user->cpucores): ?> <i class="fa fa-check"></i><?php else: ?><i class="fa fa-times"></i><?php endif; ?>
        </td>
        <td>
            <?php if($game->gpuvram <= $user->gpuvram): ?> <i class="fa fa-check"></i><?php else: ?><i class="fa fa-times"></i><?php endif; ?>
        </td>
        <td>
            <?php if($game->ram <= $user->ram): ?> <i class="fa fa-check"></i><?php else: ?><i class="fa fa-times"></i><?php endif; ?>
        </td>
        <td>
            <?php if($game->storagespace <= $user->storagespace): ?> <i class="fa fa-check"></i><?php else: ?><i class="fa fa-times"></i><?php endif; ?>
        </td>
    </tr>
    <?php endif; ?>

    </tbody>
</table>

<script>
</script>