<form action="<?php if($edit): echo '/game/editPost/' . $game->id; else: echo '/game/createPost/'; endif; ?>" method="post">
    <div class="container">
        <h1><?php if($edit): echo 'Edit'; else: echo 'Add new game'; endif; ?></h1>
        <h5>Required</h5>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="<?php if($edit): echo $game->name; endif;?>" placeholder="Name">
        </div>
        <div class="form-group">
            <label for="releasedate">Release date</label>
            <input type="date" class="form-control" id="releasedate" name="releasedate" value="<?php if($edit): echo $game->releasedate; endif;?>" placeholder="Release date">
        </div>
        <h6>Select one or more genres:</h6>
        <?php foreach($genres as $genre): ?>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="genres[]" value="<?php echo $genre->id ?>" id="genres[<?php echo $genre->id ?>]" <?php if(isset($gameGenres) && in_array($genre->id, $gameGenres)): echo 'checked'; endif;?>>
                <label class="form-check-label" for="genres[<?php echo $genre->id ?>]">
                    <?php echo $genre->name ?>
                </label>
            </div>
        <?php endforeach; ?>
        <h6>Hardware requirements</h6>
        <div class="row">
            <div class="col">
                <label for="cpufreq">CPU frequency (GHz)</label>
                <input type="number" class="form-control" step=".1" id="cpufreq" name="cpufreq" value="<?php if($edit): echo $game->cpufreq; endif;?>" placeholder="CPU frequency (GHz)">
            </div>
            <div class="col">
                <label for="cpucores">Number of CPU cores</label>
                <input type="number" class="form-control" id="cpucores" name="cpucores" value="<?php if($edit): echo $game->cpucores; endif;?>" placeholder="Number of CPU cores">
            </div>
        </div>
        <div class="form-group">
            <label for="gpuvram">GPU Video RAM (GB)</label>
            <input type="number" class="form-control" id="gpuvram" name="gpuvram" value="<?php if($edit): echo $game->gpuvram; endif;?>" placeholder="GPU Video RAM (GB)">
        </div>
        <div class="form-group">
            <label for="ram">RAM (GB)</label>
            <input type="number" class="form-control" id="ram" name="ram" value="<?php if($edit): echo $game->ram; endif;?>" placeholder="RAM (GB)">
        </div>
        <div class="form-group">
            <label for="storagespace">Storage space (GB)</label>
            <input type="number" class="form-control" id="storagespace" name="storagespace" value="<?php if($edit): echo $game->storagespace; endif;?>" placeholder="Storage space (GB)">
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
