<div class="container">
    <h1>Deals for <?php echo htmlspecialchars($game->name); ?></h1>
    <div class="row">
        <div class="col-lg-12">
            <div class="row">
                <?php foreach ($deals as $deal): ?>
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <div class="card-body">
                                <h4 class="card-title">
                                    <?php echo htmlspecialchars($deal->external) ?>
                                </h4>
                                <a href="https://www.cheapshark.com/redirect?dealID=<?php echo htmlspecialchars($deal->cheapestDealID) ?>  ">Visit store (external link)</a>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>