<div class="row">
    <div class="col-lg-1">
    </div>

    <div class="col-lg-10">

        <h1><?php echo $game->name ?></h1>
        <div>
            Release date: <?php echo $this->formatDate($game->releasedate, 'd.m.Y.') ?>
        </div>
        <br>
        <div>
            Genres: <?php foreach($game->genres as $key => $genre):
                    echo $key == array_key_first($game->genres) ? '' : ', ';
                    echo $genre->name;
                    endforeach; ?>
        </div>
        <div>
            Average rating: <?php if($game->totalratingssum && $game->totalratingscount) {echo $game->totalratingssum/$game->totalratingscount;} else {echo 'N/A';} ?>
        </div>
        <br>
    </div>
    <div class="col-lg-1">
    </div>
</div>





