<div class="d-flex justify-content-between">
    <h1>
        Games
    </h1>
    <span>
        <a class="btn btn-success float-right" style="margin:10px 0 10px 10px;" href="/game/create">Add a new game</a>
    </span>


</div>

<table class="table" id="game-table" style="empty-cells: hide">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Release date</th>
        <th>Total ratings</th>
        <th>Average rating</th>
        <th>Genres</th>
        <th>CPU frequency</th>
        <th>CPU cores</th>
        <th>GPU VRAM</th>
        <th>RAM</th>
        <th>Storage</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($games as $game): ?>
    <tr valign="middle">
        <td>
            <?php echo $game->id ?>
        </td>
        <td>
            <?php echo $game->name ?>
        </td>

        <td>
            <?php echo $game->releasedate ?>
        </td>

        <td>
            <?php echo $game->totalratingscount ?>
        </td>

        <td>
            <?php if($game->totalratingssum && $game->totalratingscount) {echo $game->totalratingssum/$game->totalratingscount;} else {echo 'N/A';} ?>
        </td>

        <td>
            <?php foreach($game->genres as $key => $genre):
                echo $key == array_key_first($game->genres) ? '' : ', ';
            echo $genre->name;
            endforeach; ?>
        </td>

        <td>
            <?php echo $game->cpufreq ?>
        </td>
        <td>
            <?php echo $game->cpucores ?>
        </td>
        <td>
            <?php echo $game->gpuvram ?>
        </td>
        <td>
            <?php echo $game->ram ?>
        </td>
        <td>
            <?php echo $game->storagespace ?>
        </td>
        <td>
            <a href="/game/edit/<?php echo $game->id ?>">Edit</a>
            |
            <?php if(!$game->deleted): ?>
            <a href="/game/delete/<?php echo $game->id ?>">Delete</a>
            <?php else: ?>
            <a href="/game/restore/<?php echo $game->id ?>">Restore</a>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>

    $(document).ready(function () {
        $('#game-table').DataTable( {
        });
    });

</script>