<div class="row">
    <div class="col-lg-1">
    </div>

    <div class="col-lg-10">

        <h1><?php echo $review->title ?></h1>
        <small>A review for <?php echo $review->game ?></small>
        <div>
            Rating: <?php echo $review->rating ?> / 10
        </div>
        <br>
        <div>
            <?php echo $review->reviewtext ?>
        </div>
        <div>
            By: <?php echo $review->user ?>
        </div>
        <br>
        <?php if($review->image): ?><img src="<?php \App\Core\Config::prependToURL() ?>/upload/<?php echo $review->image ?>"><?php endif; ?>
    </div>
    <div class="col-lg-1">
    </div>
</div>