<div class="d-flex justify-content-between">
    <h1>
        <?php if($game): ?>Reviews for <?php echo htmlspecialchars($game->name); else:?>My reviews<?php endif; ?>
    </h1>
</div>
<table class="table" id="review-table" style="empty-cells: hide">
    <thead>
    <tr>
        <th>Review ID</th>
        <th>Title</th>
        <th>Rating</th>
        <?php if(!$game): ?>
            <th>Game</th>
            <th>Actions</th>
        <?php else: ?>
            <th>Reviewer</th>
        <?php endif; ?>
    </tr>
    </thead>
    <tbody>
    <?php foreach($reviews as $review): ?>
        <tr valign="middle">
            <td>
                <?php echo $review->id ?>
            </td>
            <td>
                <a href="<?php echo \App\Core\Config::prependToURL() ?>/review/detail/<?php echo $review->id ?>"><?php echo htmlspecialchars($review->title) ?></a>
            </td>
            <td>
                <?php echo htmlspecialchars($review->rating) ?>/10
            </td>
            <?php if(!$game): ?>
                <td>
                    <?php echo htmlspecialchars($review->game) ?>
                </td>
                <td>
                    <a href="<?php echo \App\Core\Config::prependToURL() ?>/review/edit/<?php echo $review->id ?>">Edit</a> |
                    <a href="<?php echo \App\Core\Config::prependToURL() ?>/review/delete/<?php echo $review->id ?>">Delete</a>
                </td>
            <?php else: ?>
                <td>
                    <?php echo htmlspecialchars($review->user) ?>
                </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#review-table').DataTable( {
        });

    });
</script>