<div class="d-flex justify-content-between">
    <h1>
        Users
    </h1>
    <span>
        <a class="btn btn-success float-right" style="margin:10px 0 10px 10px;" href="/user/register">Add an Admin</a>
    </span>
</div>
<table class="table" id="user-table" style="empty-cells: hide">
    <thead>
    <tr>
        <th>Id</th>
        <th>Email</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($users as $user): ?>
        <tr valign="middle">
            <td>
                <?php echo $user->id ?>
            </td>
            <td>
                <?php echo htmlspecialchars($user->email) ?>
            </td>

            <td>
                <?php echo htmlspecialchars($user->firstname) ?>
            </td>

            <td>
                <?php echo htmlspecialchars($user->lastname) ?>
            </td>

            <td>
                <?php if(!$user->deleted): ?>
                <a href="/user/delete/<?php echo $user->id ?>">Delete</a>
                <?php else: ?>
                <a href="/user/restore/<?php echo $user->id ?>">Restore</a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>
    $(document).ready(function () {
        $('#user-table').DataTable( {
        });

    });
</script>