<form action="/user/loginPost" method="post">
    <div class="container">
        <h1>Login</h1>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="pass">Password</label>
        <input type="password" class="form-control" id="pass" name="pass" placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>




