
<form action="<?php echo \App\Core\Config::prependToURL(); ?>/user/loginPost" method="post">
    <div class="container">
        <h1>Login</h1>
    <div class="form-group">
        <label for="email">Email address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
        <?php if(isset($errors['login-email'])):
            foreach($errors['login-email'] as $error):?>
                <small class="text-danger"><?php echo $error; ?></small><br>
            <?php endforeach; endif; ?>
    </div>
    <div class="form-group">
        <label for="pass">Password</label>
        <input type="password" class="form-control" id="pass" name="pass" placeholder="Password">
        <?php if(isset($errors['login-pass'])):
            foreach($errors['login-pass'] as $error):?>
                <small class="text-danger"><?php echo $error; ?></small><br>
            <?php endforeach; endif; ?>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>




