<?php if($edit): ?>
<div class="d-flex justify-content-between">
    <span>
        <a class="btn btn-success float-right" style="margin:10px 0 10px 10px;" href="<?php echo \App\Core\Config::prependToURL() ?>/user/reset/<?php echo $user->id; ?>">Reset password</a>
    </span>
</div>
<?php endif; ?>
<form action="<?php echo \App\Core\Config::prependToURL(); if($edit): echo '/user/editPost/' . $user->id; else: echo '/user/registerPost/'; endif; ?>" method="post" enctype="multipart/form-data">
    <div class="container">
        <h1><?php if($edit): echo 'Edit'; else: echo 'Register'; endif; ?></h1>
        <h5>Required</h5>
        <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" name="email" value="<?php if($edit): echo htmlspecialchars($user->email); endif;?>" placeholder="Enter email">
            <?php if(isset($errors['register-email'])):
            foreach($errors['register-email'] as $error):?>
            <small class="text-danger"><?php echo $error; ?></small><br>
            <?php endforeach; endif; ?>
        </div>
        <?php if(!$edit): ?>
        <div class="form-group">
            <label for="pass">Password</label>
            <input type="password" class="form-control" id="pass" name="pass"  placeholder="Password">
            <?php if(isset($errors['register-pass'])):
                foreach($errors['register-pass'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small><br>
                <?php endforeach; endif; ?>
        </div>
        <div class="form-group">
            <label for="pass-r">Repeat Password</label>
            <input type="password" class="form-control" id="pass-r" name="pass-r" placeholder="Repeat Password">
            <?php if(isset($errors['register-pass-r'])):
                foreach($errors['register-pass-r'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small><br>
                <?php endforeach; endif; ?>
        </div>
        <?php endif; ?>

        <div class="row">
            <div class="col">
                <label for="firstname">First Name</label>
                <input type="text" class="form-control" id="firstname" name="firstname" value="<?php if($edit): echo htmlspecialchars($user->firstname); endif;?>" placeholder="First name">
                <?php if(isset($errors['register-firstname'])):
                    foreach($errors['register-firstname'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small><br>
                    <?php endforeach; endif; ?>
            </div>
            <div class="col">
                <label for="lastname">Last Name</label>
                <input type="text" class="form-control" id="lastname" name="lastname" value="<?php if($edit): echo htmlspecialchars($user->lastname); endif;?>" placeholder="Last name">
                <?php if(isset($errors['register-lastname'])):
                    foreach($errors['register-lastname'] as $error):?>
                        <small class="text-danger"><?php echo $error; ?></small><br>
                    <?php endforeach; endif; ?>
            </div>
        </div>
        <h5>Optional</h5>
        <div class="form-group">
            <label for="profileimg">Profile picture (.jpeg only, max 100kb)</label>
            <?php if($edit && $user->imageurl): ?> <img height='100px' width='200px' src="<?php echo \App\Core\Config::prependToURL() ?>/upload/<?php echo $user->imageurl ?>"><?php endif; ?>
            <br>
            <input type="file" class="form-control-file" id="profileimg" name="profileimg">
        </div>
        <?php if (isset($genres)): ?>
        <h6>Select your favorite genres</h6>
        <?php foreach($genres as $genre): ?>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" name="genres[]" value="<?php echo $genre->id ?>" id="genres[<?php echo $genre->id ?>]" <?php if(isset($userGenres) && in_array($genre->id, $userGenres)): echo 'checked'; endif;?>>
            <label class="form-check-label" for="genres[<?php echo $genre->id ?>]">
                <?php echo htmlspecialchars($genre->name) ?>
            </label>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>
        <h6>PC specifications</h6>
        <div class="row">
            <div class="col">
                <label for="cpufreq">CPU frequency (GHz)</label>
                <input type="number" class="form-control" step=".1" id="cpufreq" name="cpufreq" value="<?php if($edit): echo htmlspecialchars($user->cpufreq) ?? null; endif;?>"  placeholder="CPU frequency in GHz">
                <?php if(isset($errors['register-cpufreq'])):
                    foreach($errors['register-cpufreq'] as $error):?>
                        <small class="text-danger"><?php echo $error; ?></small><br>
                    <?php endforeach; endif; ?>
            </div>
            <div class="col">
                <label for="cpucores">CPU cores</label>
                <input type="number" class="form-control" id="cpucores" name="cpucores" value="<?php if($edit): echo htmlspecialchars($user->cpucores) ?? null; endif;?>" placeholder="Number of CPU cores">
                <?php if(isset($errors['register-cpucores'])):
                    foreach($errors['register-cpucores'] as $error):?>
                        <small class="text-danger"><?php echo $error; ?></small><br>
                    <?php endforeach; endif; ?>
            </div>
        </div>
        <div class="form-group">
            <label for="gpuvram">GPU VRAM (GB)</label>
            <input type="number" class="form-control" id="gpuvram" name="gpuvram" value="<?php if($edit): echo htmlspecialchars($user->gpuvram) ?? null; endif;?>" placeholder="GPU Video RAM in GB">
            <?php if(isset($errors['register-gpuvram'])):
                foreach($errors['register-gpuvram'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small><br>
                <?php endforeach; endif; ?>
        </div>
        <div class="form-group">
            <label for="ram">RAM (GB)</label>
            <input type="number" class="form-control" id="ram" name="ram" value="<?php if($edit): echo htmlspecialchars($user->ram) ?? null; endif;?>" placeholder="RAM in GB">
            <?php if(isset($errors['register-ram'])):
                foreach($errors['register-ram'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small><br>
                <?php endforeach; endif; ?>
        </div>
        <div class="form-group">
            <label for="storagespace">Storage (GB)</label>
            <input type="number" class="form-control" id="storagespace" value="<?php if($edit): echo htmlspecialchars($user->storagespace) ?? null; endif;?>" name="storagespace" placeholder="Storage space in GB">
            <?php if(isset($errors['register-storagespace'])):
                foreach($errors['register-storagespace'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small><br>
                <?php endforeach; endif; ?>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
