<form action="/user/resetPost/<?php echo $user->id ?>" method="post">
    <div class="container">
        <h1>Reset password</h1>
        <h5>Required</h5>
            <div class="form-group">
                <label for="pass-c">Current password</label>
                <input type="password" class="form-control" id="pass-c" name="pass-c"  placeholder="Current password">
            </div>
            <div class="form-group">
                <label for="pass">New password</label>
                <input type="password" class="form-control" id="pass" name="pass"  placeholder="New password">
            </div>
            <div class="form-group">
                <label for="pass-r">Repeat new password</label>
                <input type="password" class="form-control" id="pass-r" name="pass-r" placeholder="Repeat new password">
            </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>