<form action="<?php echo \App\Core\Config::prependToURL(); if($edit): echo '/genre/editPost/' . $genre->id; else: echo '/genre/createPost/'; endif; ?>" method="post">
    <div class="container">
        <h1>Add a new genre</h1>
        <h5>Required</h5>
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="<?php if($edit): echo htmlspecialchars($genre->name); endif;?>" placeholder="Name">
            <?php if(isset($errors['genre-name'])):
                foreach($errors['genre-name'] as $error):?>
                    <small class="text-danger"><?php echo $error; ?></small>
                <?php endforeach; endif; ?>
            <br>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
