<div class="d-flex justify-content-between">
    <h1>
        Genres
    </h1>
    <span>
        <a class="btn btn-success float-right" style="margin:10px 0 10px 10px;" href="<?php echo \App\Core\Config::prependToURL() ?>/genre/create/">Add a new genre</a>
    </span>
</div>

<table class="table" id="genre-table" style="empty-cells: hide">
    <thead>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach($genres as $genre): ?>
    <tr valign="middle">
        <td>
            <?php echo $genre->id ?>
        </td>
        <td>
            <?php echo htmlspecialchars($genre->name) ?>
        </td>
        <td>
            <a href="<?php echo \App\Core\Config::prependToURL() ?>/genre/edit/<?php echo $genre->id ?>">Edit</a>
            |
            <?php if(!$genre->deleted): ?>
            <a href="<?php echo \App\Core\Config::prependToURL() ?>/genre/delete/<?php echo $genre->id ?>">Delete</a>
            <?php else: ?>
            <a href="<?php echo \App\Core\Config::prependToURL() ?>/genre/restore/<?php echo $genre->id ?>">Restore</a>
            <?php endif; ?>
        </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<script>

    $(document).ready(function () {
        $('#genre-table').DataTable( {
        });

    });

</script>